# Generated by Django 5.0.3 on 2024-04-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_encaargado_evento_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
